# Generated by Django 3.0.8 on 2020-07-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('SAR_nonSAR', models.CharField(max_length=10)),
                ('intention', models.CharField(max_length=20)),
                ('type_of_SAR', models.CharField(max_length=20)),
            ],
        ),
    ]
