# Generated by Django 3.0.8 on 2020-07-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200717_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='date',
        ),
    ]
